# Generated by Django 2.1.1 on 2018-09-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapasien',
            name='nik',
        ),
    ]
