# Generated by Django 2.1.1 on 2018-09-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_remove_datapasien_nik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunjungan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateField(help_text='Tanggal pasien berobat')),
                ('diagnosa', models.TextField(blank=True)),
                ('tensi', models.CharField(blank=True, help_text='mmHg', max_length=15)),
                ('berat_badan', models.CharField(blank=True, help_text='Kilogram', max_length=8)),
                ('kadar_hb', models.CharField(blank=True, max_length=8)),
                ('gula_darah', models.CharField(blank=True, help_text='Kadar gula darah sewaktu', max_length=10)),
                ('kolesterol', models.CharField(blank=True, help_text='Kadar kolesterol total', max_length=10)),
                ('asam_urat', models.CharField(blank=True, help_text='Kadar asam urat', max_length=10)),
                ('pemeriksaan_lain', models.TextField(blank=True)),
                ('catatan', models.TextField(blank=True, help_text='Jika ada obat racikan tulis disini, atau tulis catatan apa saja')),
                ('obat_sudah', models.BooleanField(default=False)),
                ('nama_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran.DataPasien')),
            ],
        ),
    ]
