# Generated by Django 2.1.1 on 2018-09-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0004_auto_20180917_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resep',
            options={'verbose_name_plural': 'Resep'},
        ),
        migrations.RemoveField(
            model_name='datapasien',
            name='pendidikan_akhir',
        ),
        migrations.RemoveField(
            model_name='datapasien',
            name='status_nikah',
        ),
        migrations.AlterField(
            model_name='datapasien',
            name='alamat',
            field=models.CharField(choices=[('GT', 'Ganteng'), ('ML', 'Melayu'), ('PL', 'Pelabuhan'), ('RL', 'Ralena'), ('LT', 'Luar Tayando'), ('BT', 'Belum Diketahui')], max_length=2),
        ),
        migrations.AlterField(
            model_name='kunjungan',
            name='obat_sudah',
            field=models.BooleanField(default=False, verbose_name='Obat Sudah ?'),
        ),
        migrations.AlterField(
            model_name='kunjungan',
            name='tanggal_kunjungan',
            field=models.DateField(help_text='Tanggal pasien berobat', verbose_name='Tgl Berobat'),
        ),
        migrations.AlterField(
            model_name='resep',
            name='aturan_pakai',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
