# Generated by Django 2.1.1 on 2018-09-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0005_auto_20180919_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunjungan',
            name='rawat_inap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kunjungan',
            name='rawat_jalan',
            field=models.BooleanField(default=True),
        ),
    ]
