# Generated by Django 2.1.1 on 2018-09-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0007_auto_20180920_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunjungan',
            name='rawat_jalan',
        ),
        migrations.AddField(
            model_name='datapasien',
            name='sudah_mati',
            field=models.BooleanField(default=False, help_text='Tandai Bila Sudah Meninggal'),
        ),
        migrations.AddField(
            model_name='datapasien',
            name='tanggal_mati',
            field=models.DateField(blank=True, help_text='Tanggal Meninggal', null=True, verbose_name='Tanggal Meninggal'),
        ),
    ]
