# Generated by Django 2.1.1 on 2018-10-29 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0009_papaninformasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PapanInformasi',
        ),
    ]
