# Generated by Django 2.1.1 on 2018-10-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_informasi', models.DateField(help_text='Tanggal Pengumuman Ditulis')),
                ('judul', models.CharField(max_length=30)),
                ('isi', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Papan Pengumuman',
            },
        ),
    ]
