# Generated by Django 2.1.1 on 2018-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobat',
            name='tanggal_kadaluwarsa',
            field=models.DateField(blank=True, help_text='Masukkan tanggal ED produk yang paling dekat'),
        ),
    ]
