# Generated by Django 2.1.1 on 2018-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0002_auto_20180917_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobat',
            name='satuan',
            field=models.CharField(blank=True, choices=[('TAB', 'Tablet'), ('CAP', 'Kapsul'), ('BTL', 'Botol'), ('PCS', 'Pcs'), ('BOX', 'Box'), ('TUB', 'Tube'), ('PSG', 'Pasang')], help_text='Satuan pemakaian obat', max_length=3),
        ),
    ]
