# Generated by Django 2.1.1 on 2018-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apotek', '0003_auto_20180917_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataobat',
            name='tanggal_kadaluwarsa',
            field=models.DateField(blank=True, help_text='Masukkan tanggal ED yang paling dekat'),
        ),
    ]
